### ISSUE TITLE
Can someone explain how to get the payload out of a decoded token?

### ISSUE THREAD

**Issue by Deekor** [kylef/JSONWebToken.swift#10]
I'm at a lost as to how this works and you don't have an example in your readme.

https://stackoverflow.com/questions/32511043/jwt-decoderesult-does-not-have-a-member-named-success

**Comment by kylef** [comment]
It returns an enum which has success and failure, you can use it as follows:

```swift
let result = JWT.decode(responseContent! as String, .HS256(secret))
switch result {
case .Success(let payload):
    print(payload)
case .Failure(let failure):
    print("decoding failed \(failure)")
}
```

**Comment by Deekor** [comment]
Awesome thanks!
