### ISSUE TITLE
Ambiguous reference to member 'encode(claims:algorithm:headers:)

### ISSUE THREAD

**Issue by SwiftExpert** [kylef/JSONWebToken.swift#101]
Hi. when im using encode function i get this error: Ambiguous reference to member 'encode(claims:algorithm:headers:)'

Swift version issue i guess? are you planning to upload a new version?

![screen shot 2018-01-31 at 10 49 09 am](https://user-images.githubusercontent.com/35992075/35614075-89ef7140-0676-11e8-8b7b-0c5e7dd3639e.png)

**Comment by kylef** [comment]
I think it could be that it is treating the dictionary as `[String: String]` where the encode method expects `[String: Any]`. Does casting this possible help?

```swift
["email": ""] as [String: Any]
```

**Comment by SwiftExpert** [comment]
Tried doing it, didnt help. but figured it out. i needed to unwrap "secret".data(using: .utf8)" it returns an optional Data object. though i don't know how the error("Ambiguous reference") relates to it...

**Comment by rickrizzo** [comment]
Had this error too. It'd be great if the README were updated to reflect this fix
