### ISSUE TITLE
Invalid signature against Java JWT implementation

### ISSUE THREAD

**Issue by mejmo** [kylef/JSONWebToken.swift#115]
We are using the library but it is not possible to connect to JWT enabled services because they need to have secret base64 encoded. If we encode the password at first before pushing to the library, it is still saying that the generated JWT token is invalid. 

So basically... the token generated in Swift works when the signature is generated in JWT.io with `secret base64 encoded`, so the signature is re-generated. Such token works. How can I let the library to encode the password for me? Thanks

![image](https://user-images.githubusercontent.com/5256385/44101225-37d24602-9fe7-11e8-93c3-17c3f7fa0926.png)

**Comment by baikal23** [comment]
We are having the same problem.  Any workarounds or solutions would be much appreciated

**Comment by mejmo** [comment]
We found the issue - thing is, iOS needs the key in base64 encoded form. We were inserting the value in Java as following:
`String.getBytes()` and not `decodeBase64(String).getBytes()`. You have to check that you are providing the secret in correct form at each place. We had just two places (iOS and Java) and using the key differently (secret decoded from base64 and on the other place not). Hope this helps.

**Comment by kylef** [comment]
You can use the base64Encoded initialiser for Data: https://developer.apple.com/documentation/foundation/nsdata/1410081-init
