### ISSUE TITLE
Anyone there?

### ISSUE THREAD

**Issue by jonblatho** [kylef/JSONWebToken.swift#122]
@kylef, are you still interested in maintaining this project? If not, would you mind transferring it to someone who is? This includes me and certainly some others that have interacted with this repo in the recent past. I wouldn't normally do this, but the last commit on the master branch was almost a year ago.

There are issues and pull requests which are months old and prevent this package from building out of the box in Xcode 10 and later. I'd hate to have to switch to another JWT library because issues fixed and wishes granted in PRs are sitting around unmerged, and I'm sure others would hate to have to do so, too.

**Comment by iprasla** [comment]
I agree.

**Comment by AccuPhoenix01** [comment]
I have been using: https://github.com/radianttap/JSONWebToken.swift
which is updated  for Xcode 10 and up, Swift 5, etc.

**Comment by iprasla** [comment]
The last commit I see is from April. I am not sure if it is still updated.
