### ISSUE TITLE
JWT headers

### ISSUE THREAD

**Issue by Deekor** [kylef/JSONWebToken.swift#13]
Is there currently a way to adjust the header / insert a new value into it?

**Comment by kylef** [comment]
I'm not entirely sure what you are referring to my JWT headers @Deekor, can you please elaborate?

**Comment by Deekor** [comment]
On http://jwt.io you can see a header box with the text in red. I was hoping to add another variable to the header like a `user_id` or something.
![screen shot 2015-10-12 at 9 18 54 am](https://cloud.githubusercontent.com/assets/1904267/10431461/696e6d3c-70c2-11e5-9172-dc05b0729ec8.png)

**Comment by kylef** [comment]
@Deekor You should be placing the `user_id` inside the payload directly. Otherwise anyone can change/alter/remove the user ID and the JWT would still validate as only the body is checked (by design in JSON Web Token specification).

You can create this as follows:

```swift
let jwt = JWT.encode(.HS256("secret")) { builder in
  builder["user_id"] = "kylef"
}
```

And decode:

```swift
do {
  let payload = try JWT.decode(jet, algorithm: .HS256("secret"))
  print(payload["user_id"])
} catch {
  print("Failed to decode JWT: \(error)")
}
```

**Comment by Deekor** [comment]
Good to know I thought the signature validated the header too.Thanks.

**Comment by kylef** [comment]
@Deekor The header only contains the metadata such as the algorithm used for validating the payload.
