### ISSUE TITLE
testEncodingJWT Fails on iPhone 4S

### ISSUE THREAD

**Issue by tternes** [kylef/JSONWebToken.swift#22]
The `testEncodingJWT` test fails on iOS 8 (via Travis):

> ✗ testEncodingJWT, XCTAssertEqual failed: ("Optional("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiS3lsZSJ9.4tCpoxfyfjbUyLjm9_zu-r52Vxn6bFq9kp6Rt9xMs4A")") is not equal to ("Optional("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSJ9.zxm7xcp1eZtZhp4t-nlw09ATQnnFKIiSN83uG8u6cAg")") -

https://travis-ci.org/tternes/JSONWebToken.swift/jobs/105298771

**Comment by tternes** [comment]
This doesn't appear to be an OS issue, but possibly a 32/64 bit issue. The following test pass was done against iOS 9 with the same device (iPhone 4S) failing:

https://travis-ci.org/tternes/JSONWebToken.swift/jobs/105309981

**Comment by florentmorin** [comment]
JWT seems to use [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift), so it's probably due to a CryptoSwift issue.

**Comment by kylef** [comment]
I think it could well be a problem CryptoSwift, I haven't had chance to look into it and confirm. If anyone does I'd really appreciate it.

**Comment by tternes** [comment]
I think the problem boils down to the test assuming the order elements in the dictionary will be serialized - which happens to be different on different devices. For example, `{ "name" : "John", "age" : 27 }` and `{ "age" : 27, "name" : "John" }` are equivalent in terms of data, but their HMAC values will be very different, since the string versions are different.

I think this is probably a matter of pursuing a slightly different strategy for these tests.
