### ISSUE TITLE
Use carthage to install

### ISSUE THREAD

**Issue by xandros6** [kylef/JSONWebToken.swift#25]
I try Carthage to install this module using in cartfile:

`github "kylef/JSONWebToken.swift"`

but on `carthage update --platform iOS`

I receive the error:

`Dependency "JSONWebToken.swift" has no shared framework schemes for any of the platforms: iOS`

Can you help me?
Thanks.

**Comment by ikesyo** [comment]
Carthage support is added in #21 but a new release including it is not yet released. You can use by specifying branch as `github "kylef/JSONWebToken.swift" "master"` for now.

**Comment by xandros6** [comment]
OK, thanks, now I receive:

```
Could not pick a version for github "krzyzanowskim/CryptoSwift", due to mutually incompatible requirements:
	"0.2.3"
	"0.2.2"
```

Because my project depends from CryptoSwift but 0.2.3.
What do you think to modify your "cartfile" and support next version of CryptoSwift using version requirement `~> 0.2.2` ?

**Comment by xandros6** [comment]
Now I force my requirement of CryptoSwift to 0.2.2 but the output is the same:

`Dependency "JSONWebToken.swift" has no shared framework schemes for any of the platforms: iOS`

with version:

`*** Checking out JSONWebToken.swift at "5771d9847f0119d4151cdd197115401aa8c99aeb"`

**Comment by ikesyo** [comment]
I'm not sure why, but `JWT.xcodeproj` only have Mac target, does not support iOS target.

**Comment by xandros6** [comment]
Sorry, can't I use on iOS? Or is only a misconfiguration?

**Comment by ikesyo** [comment]
I've submitted a PR to fix this #26.

**Comment by xandros6** [comment]
Tested with your (ikesyo) fork and "carthage-other-platforms" branch, all OK, also CryptoSwift dependency!

Thanks!

**Comment by below** [comment]
Should this be fixed as of now?
