### ISSUE TITLE
CryptoSwift version is too low

### ISSUE THREAD

**Issue by arden** [kylef/JSONWebToken.swift#29]
CryptoSwift version is too low，when to update to the lately version.
when i'm pod update, now

- `CryptoSwift (= 0.2.3)` required by `Podfile`
- `CryptoSwift (= 0.2.3)` required by `Podfile`
- `CryptoSwift (= 0.2.3)` required by `Podfile`
- `CryptoSwift (~> 0.0.8)` required by `JSONWebToken (1.0.0)`

some errors like this

**Comment by kylef** [comment]
Newer versions of JSONWebToken support CryptoSwift `0.2.2`. You can upgrade or even use master which unlocks the CryptoSwift to `~> 0.2.2`.

```ruby
pod 'JSONWebToken', :git => 'https://github.com/kylef/JSONWebToken.swift'
