### ISSUE TITLE
How can I install without CocoaPods?

### ISSUE THREAD

**Issue by lostatseajoshua** [kylef/JSONWebToken.swift#31]
I want to use the project without the dependency of CocoaPods in my project. I have copied the following files: 

`Base64.swift`
`Claims.swift`
`Decode.swift`
`JWT.swift`

But I am getting errors for `import CryptoSwift`

From the JWT Xcode project what all do I need to copy to getting it running? Thank you!

**Comment by kylef** [comment]
@lostatseajoshua You will need to add the CryptoSwift dependency (https://github.com/krzyzanowskim/CryptoSwift).
