### ISSUE TITLE
Cannot find JWT

### ISSUE THREAD

**Issue by lostatseajoshua** [kylef/JSONWebToken.swift#32]
I installed the framework with cocoa pods in the time being while issue #31 is resolved.
When I `import JWT` and then try to use `JWT` it can not be found. There is no autocomplete and I can not use the decode or encode methods. I am on Xcode 7.3 Swift 2.2. I have not errors when I build and I can run but the JWT framework methods are not exposed. 

###### Updated
If you create a struct and try to call JWT it throws error expected declaration.

**Comment by kylef** [comment]
> If you create a struct and try to call JWT it throws error expected declaration

What does the error say? Can you share the exact error message?

**Comment by lostatseajoshua** [comment]
@kylef I cleaned my build and it worked!. Just Xcode throwing weird errors. Sorry about that.
