### ISSUE TITLE
Error While Installing via CocoaPods

### ISSUE THREAD

**Issue by DevPravin** [kylef/JSONWebToken.swift#38]
I have installed the 'JSONWebToken' via CocoaPods but can't build due to some errors in file CryptoSwift framework. Attached the error screen shot.
I am using CocoaPod version 1.0.1

**Comment by DevPravin** [comment]
Uploaded the error screen shot at <img width="1140" alt="pod-install-error" src="https://cloud.githubusercontent.com/assets/20066655/16229698/83d2b3e6-37db-11e6-8f28-c206493b2c71.png">

**Comment by dfmuir** [comment]
Let's see your podfile

**Comment by DevPravin** [comment]
It seems issue with Podfile. Today I tried now it's working.
Following is podfile: 

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MyAppName' do
pod 'JSONWebToken'
end

**Comment by kylef** [comment]
Could you please share your `Podfile.lock` showing the versions of dependencies used. Along with mentioning which version of Swift and Xcode you are using.
