### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by enagorny** [kylef/JSONWebToken.swift#39]
Are you planning to add swift3 support?
It's in beta now but many packages already have `swift3` branches.

**Comment by kevin-chen-bcgdv** [comment]
If you're interested, you could use my fork version for now
https://github.com/kylef/JSONWebToken.swift/pull/40

**Comment by aldocyanlabs** [comment]
@kevin-chen-bcgdv hi I'm using your fork version, but  the cryptoswift that include in your fork still in swift 2. Am i doing it wrong?

**Comment by kevin-chen-bcgdv** [comment]
@aldocyanlabs, please specify the cryptoswift in the Podfile to swift 3 branch

https://github.com/krzyzanowskim/CryptoSwift/tree/swift3

pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "swift3"

**Comment by ed-mejia** [comment]
We need an official Swift 3 branch ..

+1 this!

**Comment by nadav96** [comment]
@kevin-chen-bcgdv Hey dude awesome fork, I saw that you guided @aldocyanlabs  on how to set the CryptoSwift to the correct swift3 branch in Cocoapods, but I'm failing to do the same on Carthage, can you help?

**Comment by xmkevinchen** [comment]
@nadav96 
in the Cartfile

github 'krzyzanowskim/CryptoSwift' 'swift3'

Should work

**Comment by nadav96** [comment]
@xmkevinchen Unfortunately I already tried that, as follows:
`github "xmkevinchen/JSONWebToken.swift" "swift-3"`
`github "krzyzanowskim/CryptoSwift" "swift3"`

The problem is that that carthage is trying to build the CryptoSwift framework **twice** (once as a nested requirement in the fork, and the other for what I stated in the Cartfile)

`*** Fetching CryptoSwift
*** Fetching JSONWebToken.swift
*** Fetching CryptoSwift`

**Comment by xmkevinchen** [comment]
I'm also working on upgrading to GM Xcode version, so I'll let you know later

**Comment by xmkevinchen** [comment]
@nadav96 

BTW, what's your `xcode-select -p` output in the command line?

**Comment by nadav96** [comment]
@xmkevinchen 
`/Applications/Xcode8.app/Contents/Developer` 

*Download the GM version and moved it to the applications as Xcode8.app

**Comment by xmkevinchen** [comment]
@nadav96 

I think just put this line in Cartfile will be fine

```
github "xmkevinchen/JSONWebToken.swift"
```

**Comment by xmkevinchen** [comment]
Pull Request #43 is the latest code for supporting Xcode 8 GM

**Comment by xmkevinchen** [comment]
For CocoaPods

```
  pod 'JSONWebToken', :git => 'https://github.com/xmkevinchen/JSONWebToken.swift.git', :tag => '1.5.1'
    pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :branch => 'swift3'
```

**Comment by nadav96** [comment]
@xmkevinchen Awesome it works! Thanks.

**Comment by kylef** [comment]
Swift 3.0 support has been added in [JSONWebToken 2.0.0](https://github.com/kylef/JSONWebToken.swift/releases/tag/2.0.0).
