### ISSUE TITLE
Umbrella header 'JSONWebToken-umbrella.h' not found.

### ISSUE THREAD

**Issue by askingquestion** [kylef/JSONWebToken.swift#42]
When I run JWT, I got Umbrella header 'JSONWebToken-umbrella.h' not found.

I used cocoapods, already reinstall and still got Umbrella header 'JSONWebToken-umbrella.h' not found error.

How to correct this?
![screen shot 2016-08-01 at 11 18 22 am](https://cloud.githubusercontent.com/assets/20764452/17283403/0c6bacd0-57da-11e6-9b1e-596dfd049b37.png)

**Comment by p2** [comment]
You will get the "umbrella" error whenever a library fails to build. If you're using Xcode 8 you'll have to wait for #39.

**Comment by xmkevinchen** [comment]
@askingquestion, if you don't mind, you could just use my forked version which is described in #39

**Comment by kylef** [comment]
This should have been resolved by JSONWebToken 2.0.1.
