### ISSUE TITLE
Difference Swift 3.0 and Swift 2.0 release

### ISSUE THREAD

**Issue by ogezue** [kylef/JSONWebToken.swift#44]
I adopted to Swift 3.0 and figured out to make it work correctly. The signature gets verified if I set "secret base64 encoded" to true.

Here the code:

```
let secret = Data(base64Encoded: "My20CharSecret", options: [])
return JWT.encode(["userid": userID], algorithm: .hs256(secret! as Data))
```

Now I want to do the same for an old Swift 2.2 project.
Here the signature is only valid if I **uncheck** "secret base64 encoded".
Here the code:
`return JWT.encode(["userid": userID], algorithm: .HS256("My20CharSecret"))`

What do I have to do to get a verification with the "secret base64 encoded" checked?

**Comment by kylef** [comment]
Only JSONWebToken 2.0.1 supports passing data to encode/decode. Older versions of JSONWebToken must take strings.
