### ISSUE TITLE
watchOS error with Carthage

### ISSUE THREAD

**Issue by hamchapman** [kylef/JSONWebToken.swift#47]
Xcode: 8.0 (8A218a)
Sierra 10.12
JSONWebToken.swift version 2.0.1

`Cartfile`:

```
github "kylef/JSONWebToken.swift" == 2.0.1
```

`Cartfile.resolved`:

```
github "krzyzanowskim/CryptoSwift" "0.6.0"
github "kylef/JSONWebToken.swift" "2.0.1"
```

When using Carthage to install the library (running `carthage update` I'm getting this error, in relation to CryptoSwift.

```
/DerivedData/JWT-grekwtpopyeadqfzzrcglfxcjnno/Build/Intermediates/JWT.build/Release-watchos/JWT-watchOS.build/Objects-normal/armv7k/Base64.bc
/Users/Hami/Pusher/elements-client-swift/Carthage/Checkouts/JSONWebToken.swift/Sources/JWT.swift:2:8: error: module file's minimum deployment target is watchos3.0 v3.0: /Users/Hami/Library/Developer/Xcode/DerivedData/JWT-grekwtpopyeadqfzzrcglfxcjnno/Build/Products/Release-watchos/CryptoSwift.framework/Modules/CryptoSwift.swiftmodule/arm.swiftmodule
import CryptoSwift
       ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal armv7k /Users/Hami/Pusher/elements-client-swift/Carthage/Checkouts/JSONWebToken.swift/Sources/Claims.swift
	CompileSwift normal armv7k /Users/Hami/Pusher/elements-client-swift/Carthage/Checkouts/JSONWebToken.swift/Sources/JWT.swift
	CompileSwift normal armv7k /Users/Hami/Pusher/elements-client-swift/Carthage/Checkouts/JSONWebToken.swift/Sources/Decode.swift
	CompileSwift normal armv7k /Users/Hami/Pusher/elements-client-swift/Carthage/Checkouts/JSONWebToken.swift/Sources/Base64.swift
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(5 failures)
```

The target I'm trying to add this to is a target with support for iOS, tvOS, macOS and watchOS.

**Comment by hamchapman** [comment]
After some testing, this looks like a problem with Crytoswift and it not specifying deployment targets for tvOS or watchOS. I've made a pull request to update it here: https://github.com/krzyzanowskim/CryptoSwift/pull/357

**Comment by emaloney** [comment]
I just hit the exact same problem myself. Would be great to be able to compile for tvOS 9.x and watchOS 2.x, especially since I've already shipped a tvOS 9.x app that includes CryptoSwift.

**Comment by hamchapman** [comment]
`github "hamchapman/JSONWebToken.swift" "update-cryptoswift-dependency"` will work if you need a temporary fix!

**Comment by emaloney** [comment]
Thanks, @hamchapman.

BTW, looks like your pull request got merged into `develop` within seconds of my message. Fast service!

**Comment by kylef** [comment]
Great, I'm gonna close this since it's been fixed upstream.

**Comment by kylef** [comment]
Thanks for digging into this and resolving the underlying issue @hamchapman.
