### ISSUE TITLE
New tag with ClaimSet changes

### ISSUE THREAD

**Issue by dannylewis-sheffield** [kylef/JSONWebToken.swift#53]
Hi

Can you tag the code if you think it's stable with the ClaimSet changes.  See #49 

Thanks

**Comment by kylef** [comment]
-> https://github.com/kylef/JSONWebToken.swift/releases/tag/2.1.0

**Comment by dannylewis-sheffield** [comment]
Hi

Thanks for doing this, I appreciate your code and contributions to the community.

Best regards
Danny
