### ISSUE TITLE
Not all classes being downloaded with the Pod

### ISSUE THREAD

**Issue by JaapWeijland** [kylef/JSONWebToken.swift#58]
I installed JWT through cocoapods. pod 'JSONWebToken'. The example tells me to use the ClaimSet class, which isn't downloaded.  The only classes downloaded are Base64, Claims, JWT, and Decode. Xcode doesn't recognize any other classes mentioned in the guides (makes sense, since they don't appear in my pod workspace either).

**Comment by kylef** [comment]
@JaapWeijland Which version did you install with CocoaPods?

**Comment by JaapWeijland** [comment]
Dont know, how can I see that? I just installed by adding pod 'JSONWebToken'. Found out just now that installing this with this line "pod 'JSONWebToken', :git => 'https://github.com/kylef/JSONWebToken.swift.git'" does work.

**Comment by SpacyRicochet** [comment]
Just encountered the exact same issue. Mostly likely cause is your CocoaPods repository cache not being up to date.

For anyone coming here in the future, try the following;

```> pod repo update
> pod install```
