### ISSUE TITLE
Ambiguous use of decode (v. 2.1.0)

### ISSUE THREAD

**Issue by tuxfamily** [kylef/JSONWebToken.swift#59]
Hello.

After an upgrade from JSONWebToken 2.0.1 to 2.1.0

I get the following error:
Ambiguous use of 'decode(_:algorithm:verify:audience:issuer:)'

My code
`let payload = try JWT.decode(cryptedResponse, algorithm: .hs256((api.key).data(using: .utf8)!))`

And when I click on "decode", XCode leads me to this
`typedef struct vImage_CGImageFormat
{
    uint32_t                bitsPerComponent;
    uint32_t                bitsPerPixel;       
    CGColorSpaceRef         colorSpace;         
    CGBitmapInfo            bitmapInfo;         
    uint32_t                version;            
    const CGFloat *         decode;
    CGColorRenderingIntent  renderingIntent;
}vImage_CGImageFormat;`

Which has nothing to do with JWT, but with the Accelerate framework (that I don't use...).

I've tried to clean the project, removed the derived data, and even upgraded my XCode from 8.1 to 8.2, but still ...

I finally downgraded your lib from 2.1.0 to 2.0.2, and the error is gone.

Hope this report can help.

Thanks.

**Comment by treaves** [comment]
The issue is that there are now duplicate method signatures for the two decode functions.  They return different types.  To disambiguate you need to use the type for the variable or constant name.
`let claims : ClaimSet = `
instead of:
`let claims = `
