### ISSUE TITLE
Subject (sub) claim

### ISSUE THREAD

**Issue by Headstock67** [kylef/JSONWebToken.swift#61]
I was hoping that I would be able to create tokens within the app to create a custom login to Firebase 3. However this requires that the Subject (sub) claim be set as per below:

"sub	Subject	Must be a non-empty string and must be the uid of the user or device."

Is this something that can be supported please?

**Comment by kylef** [comment]
@Headstock67 It's already supported, you can supply the `sub` claim when encoding: https://github.com/kylef/JSONWebToken.swift#encoding-a-claim

**Comment by Headstock67** [comment]
Thanks for super quick response, I'll give it a go.
