### ISSUE TITLE
pod install installs version 2.0.2 and not 2.1.0

### ISSUE THREAD

**Issue by Headstock67** [kylef/JSONWebToken.swift#62]
Hi there

2.1.0 does not install via pod (using cocoapod 1.2.0)

I've tried 'pod repo update' before 'pod install' and I have also tried changing the podfile.lock entry from: 
'JSONWebToken (2.0.2):
    - CryptoSwift (~> 0.6.1)' 
to:
 'JSONWebToken (2.1.0):
    - CryptoSwift (~> 0.6.1)'

but get the error: _[!] Unable to satisfy the following requirements:

- `JSONWebToken` required by `Podfile`
- `JSONWebToken (= 2.1.0)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `JSONWebToken, JSONWebToken (= 2.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile._

More information below:

Included in my pod file:
  pod 'JSONWebToken’

running 'pod install' generates:

 Using JSONWebToken (2.0.2)
 Generating Pods project
 Integrating client project
 Sending stats

podfile.lock

PODS:
  - CryptoSwift (0.6.7)
  - Firebase/Core (3.14.0):
    - FirebaseAnalytics (= 3.7.0)
    - FirebaseCore (= 3.5.1)
  - Firebase/Database (3.14.0):
    - Firebase/Core
    - FirebaseDatabase (= 3.1.2)
  - FirebaseAnalytics (3.7.0):
    - FirebaseCore (~> 3.5)
    - FirebaseInstanceID (~> 1.0)
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseCore (3.5.1):
    - GoogleToolboxForMac/NSData+zlib (~> 2.1)
  - FirebaseDatabase (3.1.2):
    - FirebaseAnalytics (~> 3.7)
  - FirebaseInstanceID (1.0.9)
  - GoogleToolboxForMac/Defines (2.1.1)
  - GoogleToolboxForMac/NSData+zlib (2.1.1):
    - GoogleToolboxForMac/Defines (= 2.1.1)
  - JSONWebToken (2.0.2):
    - CryptoSwift (~> 0.6.1)

DEPENDENCIES:
  - Firebase/Core
  - Firebase/Database
  - JSONWebToken

SPEC CHECKSUMS: ...........

**Comment by Headstock67** [comment]
I have resolved the problem.

Instead of adding pod 'JSONWebToken' to the podfile as per the instructions on the GitHub page. 

I changed it to explicitly point it to the URL where the latest version is held.

pod 'JSONWebToken', :git => 'https://github.com/kylef/JSONWebToken.swift'

I am new to cocoapod so this may have been obvious to most but hopefully this information will help others.

**Comment by kylef** [comment]
I think what you needed to do before was `pod update`, to update the version of JSONWebToken in your lock file.

**Comment by albertoig** [comment]
this happends too with package installation, install version 2.0.2
