### ISSUE TITLE
Unable to decode Payload other than [String: Any]

### ISSUE THREAD

**Issue by IrfanMarwat** [kylef/JSONWebToken.swift#65]
I am receiving Array of objects encoded from server. But since Payload is of type [String: Any], so its not decoding the array (json array).

**Comment by kylef** [comment]
Hi @IrfanMarwat, I'm not sure I understand the problem. Would you be able to share perhaps a small code example or some more information to help me understand please.

**Comment by IrfanMarwat** [comment]
My server is encoding something like this:

[
  {
    "key1": 1,
    "key2": "value2"
     ---
  }, 
  {
    "key1": 1,
    "key2": "value2"
     ---
  }
---
]

Top level is Array, inside array are Dictionaries.

When I tried to decode this type of encoded data, Its not able to decode. 

As this line in Decode.swift:

let payload = (try? JSONSerialization.jsonObject(with: payloadData!, options: JSONSerialization.ReadingOptions(rawValue: 0))) as? Payload

is unable to cast the result into Payload(Dictionary).

**Comment by kylef** [comment]
@IrfanMarwat Could you please link me to the part of the JWT specification where it shows that is permitted? I do not see that.

> ##### JWT Claims Set
> A string representing a JSON **object** that contains the claims conveyed by the JWT. When the JWT is signed, the bytes of the UTF-8 representation of the JWT Claims Set are base64url encoded to create the Encoded JWS Payload. When the JWT is encrypted, the bytes of the UTF-8 representation of the JWT Claims Set are used as the JWE Plaintext.

**Comment by IrfanMarwat** [comment]
This is data encoded by PHP using key secret and hs256. On online editor I am able to decode this.
https://jwt.io/

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.W3sia2V5MSI6InZhbHVlMSIsImtleTIiOiJ2YWx1ZTIiLCJrZXkzIjoidmFsdWUzIn0seyJrZXkyMSI6InZhbHVlMSIsImtleTIyIjoidmFsdWUyIiwia2V5MjMiOiJ2YWx1ZTMifV0.oGkq_l1fjJjgDrOTeBLeBPIMq1SnIjSPPjVUIVuJYj4

**Comment by kylef** [comment]
The JSON Web Token RFC 7519, section 7.2. Validating a JWT states:

> 10.  Verify that the resulting octet sequence is a UTF-8-encoded representation of a completely valid JSON object conforming to RFC 7159 [RFC7159]; let the JWT Claims Set be this JSON object.

The JWT specification declares that the claims set is to be a JSON object.

I'm going to close this issue, we can reopen it if you can find some section of the JSON Web Token specification that states an array is permitted.

**Comment by IrfanMarwat** [comment]
ok thanks for the clarification.

**Comment by SpacyRicochet** [comment]
As an interesting addition, the jwt.io decoder is indeed not strict enough. Here is the founder of Auth0 weighing in on Twitter; https://twitter.com/woloski/status/869206785193893888

**Comment by Tom29** [comment]
Hi there, i return json object but there's no way to decode it.

`
{
  "data": {
    "expiresDateMs": 123,
    "purchaseDateMs": 456
  },
  "exp": 1544347917,
  "iat": 1544347907,
  "nbf": 1544347907
}
`
How the hell can i decode `data` value?
