### ISSUE TITLE
Problem with "krzyzanowskim/CryptoSwift"

### ISSUE THREAD

**Issue by xandros6** [kylef/JSONWebToken.swift#66]
I have a project with both "krzyzanowskim/CryptoSwift" and "kylef/JSONWebToken.swift".
But the latest version of CryptoSwift is 0.6.8 and the latest used by JSONWebToken is 0.6.1, so at runtime it uses the 0.6.1 and I receive : 

> Message from debugger: Terminated due to signal 9

**Comment by kylef** [comment]
JSONWebToken depends on CryptoSwift `~> 0.6.1` which includes all releases of CryptoSwift after 0.6.1 until 0.7.0. `0.6.8` is allowed with the optimistic range specified.
