### ISSUE TITLE
Requesting new release tag (2.1.1) for SwiftPM

### ISSUE THREAD

**Issue by jarrodparkes** [kylef/JSONWebToken.swift#67]
Currently, the latest release v2.1.0 doesn't include the PR (which adds the correct Foundation imports to `ClaimSet.swift` and `Encode.swift`) causing build errors. If you don't mind releasing a new version (v.2.1.1), that'd be great 👍

**Comment by kylef** [comment]
https://github.com/kylef/JSONWebToken.swift/commit/7cb91b9533c735e9d1325ea66be8795fae6e0a74
