### ISSUE TITLE
Is there any Objective C implementation of creating JSON Web Token.

### ISSUE THREAD

**Issue by subinrevi** [kylef/JSONWebToken.swift#7]

**Comment by kylef** [comment]
As discussed [on twitter](https://twitter.com/kylefuller/status/590577501723828224), I don't know of any and I'd suggest you just write a thin wrapper around the Swift variant, or just use the swift version directly.

**Comment by benguild** [comment]
FYI for all that find this, I wrote an Objective-C wrapper for this in just a few minutes. Is there any chance we could just bundle one with the library? I mean, worst case it could be removed if it HAD to be deprecated for some reason, but it seems worthwhile to open the door to the library to all of those existing Objective-C apps.

**Comment by asib** [comment]
@benguild Could you possibly explain how you managed to do this? I can't seem figure out how...

**Comment by benguild** [comment]
@asib Certain elements of Swift aren't translated to Objective-C automatically. So, you write Swift code that can be translated to Objective-C automatically that wraps this library. :)

**Comment by asib** [comment]
@benguild Would you be able to make a gist of your wrapper if you still have it? I'd be extremely grateful!

**Comment by benguild** [comment]
It's an incomplete implementation. I did consider it at the time, but it's not for general purpose use. More just for my software's needs.

It wasn't difficult. What are you having trouble with?

**Comment by asib** [comment]
Sorry, I'm being a pain. I think I've put something reasonable together, I just wanted to cross-reference to see if I'd done something bone-headed, non-idiomatic, etc.
