### ISSUE TITLE
Adding to the Header

### ISSUE THREAD

**Issue by genedelisa** [kylef/JSONWebToken.swift#74]
You hardcode the header like this in Encode.swift

    let header = encodeJSON(["typ": "JWT", "alg": algorithm.description])!

The new Apple MusicKit framework requires a key "kid" in the header.
Since there doesn't seem to be a way to add to the header, I had to make the modification in Encode.swift.

Consider adding this capability to your library.

See [MusicKit](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/AppleMusicWebServicesReference/SetUpWebServices.html#//apple_ref/doc/uid/TP40017625-CH2-SW1)

**Comment by kylef** [comment]
@genedelisa I've added support for this in a4ce3ac which can be found in master. For now you will have to depend on master to use this functionality, it will make it into the next release soon.

**Comment by genedelisa** [comment]
Good work. Thank you.
