### ISSUE TITLE
Support for Swift 2.1

### ISSUE THREAD

**Issue by rudresha** [kylef/JSONWebToken.swift#80]
Hi ,
can you please provide version of lib that support swift 2.1 ? It would be of G8 help !

**Comment by kylef** [comment]
Hi, you can use version [1.5.0](https://github.com/kylef/JSONWebToken.swift/releases/tag/1.5.0) of the library. That should be the last version that works with Swift 2.1.

Swift 2.1 is really old though, I'd recommend using Swift 3/4 which is what future development of this library will support.
