### ISSUE TITLE
Xcode 9 beta 5 build failed

### ISSUE THREAD

**Issue by sathishkraj** [kylef/JSONWebToken.swift#81]
Xcode 9 beta 5, swift 3.2 with carthage version 0.23.0, currently using "kylef/JSONWebToken.swift" "2.1.0" version. fails building CryptoSwift

**Comment by sathishkraj** [comment]
got it, confused with swift 4 complier. using "master" solved it

**Comment by sathishkraj** [comment]
but "2.1.0" should compile in xcode 9 right. will there be any fix for this error? Build Failed Task failed with exit code 65:, This usually indicates that project itself failed to compile.

**Comment by kylef** [comment]
https://github.com/kylef/JSONWebToken.swift/releases/tag/2.2.0 works with Swift 4.
