### ISSUE TITLE
Build Failed on Xcode 9 Beta 6

### ISSUE THREAD

**Issue by Tim77277** [kylef/JSONWebToken.swift#82]
It shows No module found, and CyptoSwift files appears with many syntax error. I have tried to install it on Xcode 8 and it worked fine. But I am trying to use the Apple Music API which requires Xcode 9 Beta 6, can you confirm the error when you have time, please? Thank you

**Comment by kylef** [comment]
@Tim77277 Are you hitting the same problem by installing JSONWebToken from master? I think that should solve problems with CryptoSwift.

**Comment by Tim77277** [comment]
All I did was put the pod 'JSONWebToken' in my pod file and pod nstall. Should I install a different version?

**Comment by Tim77277** [comment]
@kylef
I just tried to install from master branch and it fixed the problem.

For people who encounter the same issue as me, can just replace this line in your pod.
 
`pod 'JSONWebToken', :git => 'https://github.com/kylef/JSONWebToken.swift.git', :branch => 'master' `

Thanks for the help

**Comment by jmprice18** [comment]
@kylef Are there plans to do a release with current `master` changes?  Cannot specify branch or commit in a podspec file.

**Comment by mkBajaj** [comment]
Is there way to include master branch in private pod spec file , Currently I am using 
pod 'JSONWebToken'   in private pod spec which is gives above same issue in Xcode beta 6. Please help , Thank you.

**Comment by marcioarantes-ww** [comment]
@kylef any idea when you'll be able to publish master? as @jmprice18 mentioned podspec versioning isn't supported :/

**Comment by marcioarantes-ww** [comment]
@kylef https://github.com/krzyzanowskim/CryptoSwift/releases/tag/0.7.0

**Comment by kylef** [comment]
https://github.com/kylef/JSONWebToken.swift/releases/tag/2.2.0
