### ISSUE TITLE
it can't be used in Swift4

### ISSUE THREAD

**Issue by gongyucheng** [kylef/JSONWebToken.swift#85]

**Comment by kylef** [comment]
Can you share a bit more info such as the platform or some build error?

The Xcode project attached builds find with Swift 4.

**Comment by JanBrinker** [comment]
I'm interested in this aswell. Basically it's the dependency to CryptoSwift. When compiling my project with Xcode 9 I don't get any errors in the JSONWebToken pod but in CryptoSwift:

<img width="976" alt="bildschirmfoto 2017-09-22 um 11 11 28" src="https://user-images.githubusercontent.com/11256194/30737461-0bc3e09a-9f87-11e7-96fc-b6605fa46817.png">

I think the current CryptoSwift (0.7.2) does support Swift 4, so I guess only the dependency needs to be updated and a new pod version released. Could you do that @kylef ? :)

**Comment by kylef** [comment]
@JanBrinker Are you using JSONWebToken 2.2.0? CryptoSwift shouldn't be used when building in Xcode.

**Comment by JanBrinker** [comment]
I'm terribly sorry to have bothered, you were completely right. Things look well now :) 👍

**Comment by kylef** [comment]
That's great to hear updating solve this for you.

Thanks for reporting here @JanBrinker.
